require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'Safarnama' do
  # use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'

  target 'SafarnamaTests' do
    inherit! :complete
    # Pods for testing
  end

  pod 'rn-fetch-blob',
  :path => '../node_modules/rn-fetch-blob'


  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Safarnama-tvOS' do
  # Pods for Safarnama-tvOS

  target 'Safarnama-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
